apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nsds-be
spec:
  replicas: 1
  minReadySeconds: 60 
  template:
    metadata:
      labels:
        app: nsds-be
    spec:
      containers:
      - name: nsds-be
        image: registry.gitlab.com/icu-development/scholar:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: management.health.show-details
          value: always
        - name: management.endpoints.web.exposure.include
          value: loggers,metrics,prometheus
        - name: spring.datasource.url
          value: "jdbc:postgresql://postgres:5432/nsds"
        - name: spring.datasource.username
          value: postgres
        - name: spring.datasource.password
          value: postgres
        - name: spring.rabbitmq.cluster
          value: UNI_TEST
        - name: spring.rabbitmq.host
          value: 93.183.196.93
        - name: spring.flyway.user
          value: postgres
        - name: spring.flyway.password
          value: postgres
        - name: spring.profiles.active
          value: "metadata,streaming,thumbnail,deployment"
        - name: azure.account.name
          value: nsds
        - name: azure.account.key
          value: "aETtI/45nOefjYCU7iQnmgY5v7S2xMubPDOedGhII3smuURLS+HWj9TFqbmFBn/pKlYbvIuFlPqANUwlsoEQEw=="
        - name: azure.account.container
          value: nsdsdev
        - name: bo.searcher.uri
          value: http://93.183.196.93:9090
        - name: keycloak.auth-server-url
          value: https://accounts-dev.universalna.com:443/auth
        - name: keycloak.realm
          value: FIRST.REALM
        - name: keycloak.resource
          value: weblogin
        - name: keycloak.realm-key
          value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnSti1E/uyi70uM8QJhGNZPiEMpM6WmxRfdFklIz3Tzec1KzWKh1tBMYTN4p+oX9wYd/y5xYtHYllDoevGvWGQ1gOyhNCHPtUSByUc5oKycXkgUF2YA3lpdbhsQpnafkMmCY/F08SF88k6uqVJXn310v3R6/NN0d8jYoIRpjNWnYPBuZoLoaeG2nBC7rF+ahH66jxFYFx7hCeBLxobkPcLMWWb5iL1HQRG86aAHIPKn/9ROGDDWN43a3TgoYZpz/aThpe4wo1Z9cLGpUkUM4tD5FdzOaGrlUEmCom+X+t+lRBoCgd8XIlxlLD6xLL6jpsJcf5ldgJHH97g9BsKCzsBwIDAQAB
        - name: azure.oauth2.clientId
          valueFrom:
            secretKeyRef:
              name: nsds-be-secret
              key: azure_oauth2_clientId
        - name: azure.oauth2.clientSecret
          valueFrom:
            secretKeyRef:
              name: nsds-be-secret
              key: azure_oauth2_clientSecret
        - name: azure.oauth2.scope
          value: "User.Read offline_access"
        - name: azure.oauth2.username
          valueFrom:
            secretKeyRef:
              name: nsds-be-secret
              key: azure_oauth2_username
        - name: azure.oauth2.password
          valueFrom:
            secretKeyRef:
              name: nsds-be-secret
              key: azure_oauth2_password
        - name: spring.redis.host
          value: "redis-master"
        - name: spring.redis.port
          value: "6379"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "600Mi"
          limits:
            memory: "2500Mi"
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: nsds-be
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nsds-be
  type: ClusterIP
