-- TODO: add ID reference to metadata
CREATE TABLE METADATA_AUDIT (ID                    UUID,
                             NAME                  VARCHAR(100),
                             SIZE                  BIGINT,
                             RELATION              VARCHAR(255),
                             RELATION_ID           VARCHAR(255),
                             DESCRIPTION           TEXT,
                             UPLOADER_ID           VARCHAR(255),
                             TIMESTAMP             TIMESTAMPTZ,
                             SOURCE                VARCHAR(255),
                             ORIGIN                VARCHAR(255),
                             STATUS                VARCHAR(255),
                             FILE_STORAGE_FILE_ID  TEXT,
                             PREVIEW               TEXT,
                             TAGS                  JSONB,
                             CREATED_DATE          TIMESTAMPTZ,
                             CREATED_BY            VARCHAR(255),
                             LAST_MODIFIED_DATE    TIMESTAMPTZ,
                             LAST_MODIFIED_BY      VARCHAR(255),
                             AUDIT_REVISION        BIGINT REFERENCES revinfo(rev),
                             AUDIT_REVISION_END    BIGINT,
                             AUDIT_REVISION_END_TS TIMESTAMPTZ,
                             ACTION_TYPE           SMALLINT NOT NULL,
                             PRIMARY KEY (ID, AUDIT_REVISION)
)