CREATE TABLE BOOKMARK (OWNER       VARCHAR(255) CONSTRAINT OWNER       NOT NULL,
                       RELATION    VARCHAR(255) CONSTRAINT RELATION    NOT NULL,
                       RELATION_ID VARCHAR(255) CONSTRAINT RELATION_ID NOT NULL,
                       PRIMARY KEY (OWNER, RELATION, RELATION_ID)
)

